apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: orders-server-replica-set
spec:
  replicas: 5
  selector:
    matchExpressions:
      - key: app-name
        operator: In
        values:
          - orders-server
  template:
    metadata:
      labels:
        app-name: orders-server
    spec:
      containers:
        - name: orders-server
          image: acaban/orders
          ports:
            - containerPort: 8080
              name: http
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: payments-server-replica-set
spec:
  replicas: 5
  selector:
    matchExpressions:
      - key: app-name
        operator: In
        values:
          - payments-server
  template:
    metadata:
      labels:
        app-name: payments-server
    spec:
      containers:
        - name: payments-server
          image: acaban/payments
          ports:
            - containerPort: 8080
              name: http
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: products-server-replica-set
spec:
  replicas: 5
  selector:
    #matchLabels:
    #  app-name: echo-server
    matchExpressions:
      - key: app-name
        operator: In  # (In, Notin, Exists)
        values:
          - products-server
  template:
    metadata:
      labels:
        app-name: products-server
    spec:
      containers:
        - name: products-server
          image: acaban/products
          ports:
            - containerPort: 8080
              name: http
